---
permalink: /blog/2010/06/18/modernizing-research-through-collaborative-reference-tools-the-medieval-slavic-linguistics-wiki/
title: "Modernizing Research through Collaborative Reference Tools: The Medieval Slavic Linguistics Wiki"
date: 2010-06-18
classes: wide
show_date: true
---
<p><em>As a way of setting an actual deadline for myself to make some progress on the Medieval Slavic wiki, I submitted an abstract to the Fifth Annual Meeting of the Slavic Linguistic Society, which follows.</em></p>
<p> The rise in scholarly materials accessible through Internet (JSTOR, SpringerLink, and/or PDFs published by individuals) has facilitated the research process for scholars worldwide. For Slavic linguists, however, many of the major reference works were published over 50 years ago, and are unavailable electronically. The success of Wikipedia as a general reference source for laypeople illustrates the potential of wikis as a way of organizing information from diverse sources. This paper aims to make the case for developing a separate wiki as a shared reference resource for Slavic linguists.</p>
<p>While on­line publication of materials lowers one barrier to access, the research process itself has largely remained the same. It is often necessary for scholars to seek out information from areas where they are less familiar with the literature. This can involve consulting a reference work and tracking the topic through bibliographies. The amount of time necessary to look up facts takes away from the time the scholar can devote to the intellectual content of their research.</p>
<p>A common approach to solving this problem is scanning materials. However, a tremendous amount of tedious work is involved in this process, and copyright is a non­trivial concern. A specialized wiki, compiled by Slavic linguists and Slavic linguistics graduate students, would reduce both tedium and copyright concerns, as the facts and conjectures contained within monographs and articles are not themselves subject to copyright.</p>
<p>A test case is currently being developed, limited to topics  relevant to medieval Slavic linguistics. The wiki contains two kinds of content: article/monograph summaries that lay out the major claims of a particular work, and topic-­based pages that bring together both undisputed facts and various conflicting scholarly claims on the topic, drawn from articles and monographs. Both kinds of wiki pages include copious, specific footnotes referencing the source material­­ both to enable fact­-checking and to allow the scholar to cite the original material rather than the wiki if desired.</p>
<p>Mediawiki, the wiki software developed for Wikipedia also used for this test case, includes a number of features aimed to both encourage contribution and prevent abuse. Each user account comes with a page linking to that user's contributions on each of the pages where they have added (or removed) something. Even scholars without any specialized technology skills can contribute to the wiki, and include the link to their contributions on their CV to show their involvement in a digital humanities project. Every change made to a page is tracked in the database, and can be viewed, discussed, and/or reverted in cases of blatant abuse. The common graduate student assignment of writing article summaries could be redirected slightly towards writing summaries for articles not currently on the wiki, and breaking the information in those articles down into specific claims that can be added to topical pages encourages students to develop their analytic skills.</p>
<p>In addition to arguing for the benefits such a wiki could provide the Slavic linguistics scholarly community, this paper will present a live demonstration of the Medieval Slavic linguistics wiki.</p>
