---
permalink: /blog/2012/01/27/drupal-humanists/
title: "Drupal for Humanists"
date: 2012-01-26
classes: wide
show_date: true
---
<p>One question I continue to hear from digital humanists and higher ed IT folks is "what book should I pick up to learn Drupal?" I never have a particularly good answer-- not because there aren't any good books out there (I assume there are), but because I've never used one. I learned Drupal 4 through trial and error, while not paying attention in a biology class I needed to fulfill a distribution requirement that I'd put off until my last year of college. I figured out Drupal 5 and 6 (much like Drupal 4, but greatly improved) because I needed a CMS for a project and I ended up learning a lot in the process. Every time I need to do something new with Drupal, I Google until I figure it out, and then I know one more thing.</p>
<p>Not the most helpful response for people who prefer to have a book on hand as they're learning.</p>
<p><a href="http://www.flickr.com/photos/quinnanya/5394498354/" title="Notes by quinn.anya, on Flickr"><img src="http://farm6.staticflickr.com/5135/5394498354_fcc96a9e9c_m.jpg" width="160" height="240" alt="Notes" class="alignright" /></a>What's surprised me is that when I shrug and tell people there's stuff out there but I can't recommend any titles from personal experience, the reply has often enough been, "Why don't you write one?" I was pretty dismissive of the idea at first-- I'm generally inclined towards just posting things online-- but after enough repetitions of this conversation, I started to consider it. There's something to be said for a book with a clear presentation of Drupal, arranged in a coherent and logical way, covering "why Drupal?" and when to <strong>not</strong> use Drupal, and everything from installation to <a href="http://drupal.org/project/ds">Display Suite</a> magic for the adventurous. I really do think that anyone can build sites in Drupal, even the tech-hesitant, if someone does a good enough job walking through the process. Unlike WordPress, Drupal isn't inclined to hold your hand, but maybe a book on Drupal geared towards humanists (digital or not) and the techies who work with them could bridge that gap.</p>
<p>I consulted with fellow Drupal guru <a href="https://dhs.stanford.edu/author/emeeks">Elijah Meeks</a> (whose work on spatial Drupal blows <em>my</em> mind), and we decided we're going to co-author "Drupal for Humanists" and get it published. The first part of the book will cover how to build Drupal sites in general (including modules, content types, site design, etc.), and the second part of the book will be case studies, looking at what modules and configuration settings go into the kinds of sites that are particularly relevant for humanists. Each case study will conclude with a section about how that kind of site might evolve, based on our experience building them.</p>
<p>We're looking for feedback on the case studies (especially the one on multimedia) and suggestions for anything we missed, so if you have a moment, please check out the <a href="http://bit.ly/wmOOG7">Google Doc with the case study outlines</a> and leave some comments.</p>
