---
permalink: /blog/2020/05/28/remarks-dh-methods-and-tools-gone-wrong-discoveries-failures-advice-future/
title: "Remarks for 'DH Methods and Tools Gone Wrong: Discoveries, Failures & Advice for the Future'"
date: 2020-05-28
classes: wide
show_date: true
---
<p><em>These were my 3-minute comments for a small-group discussion at the <a href="https://www.dariah.eu/2020/05/14/dariah-virtual-exchange-session-what-is-coming-next/">DARIAH VX</a> Breakout session 4: DH Methods and Tools Gone Wrong: Discoveries, Failures & Advice for the Future on May 28, 2020.</em></p>
<p>For the last year or so, Alex Wermer-Colan and I have been working on the start of a book abut failure and digital humanities. The most interesting thing we’ve found so far may be some people’s resistance to the idea of “failure”. We’ve had people ask us to use some other term. We’ve had other people flat-out deny that there’s ever any failure in digital humanities. It’s just an experiment! A prototype! It’s never “failure”.</p>
<p>We disagree with a hard-line “failure denialism” stance, but clearly there’s a difference between trying out an algorithm that doesn’t work out, and promising to build a scalable, sustainable technical infrastructure for a field, using significant financial and volunteer resources, and producing nothing substantive. Failure is contextual.</p>
<p>I think the framing of this virtual exchange session, “The Scholarly Primitives of Scholarly Meetings” gets at a crucial issue as we grapple with the question of “what do we do now?” — and more importantly, “what do we do next?”</p>
<p>It’s been 7 years since I gave the talk about the failure of Project Bamboo — which once tried to create a consortium of DH infrastructures with DARIAH. 7 years. I was pregnant at the time, and that kid is now an older brother twice over, and an expert fisherman in Animal Crossing on the Nintendo Switch.</p>
<p>I’ve heard from a lot of people over the years that that talk, and the resulting paper, were really useful. And I haven’t stopped talking about failure since, with a forthcoming paper on the DiRT directory, and failure and frustration an ongoing theme in my more recent work on Multilingual DH and the Data-Sitters Club. But for all the talk about how we should “have more conversations about failure”, I haven’t seen a lot of people taking up that flag — with the notable exception of Shawn Graham, whose recent book, “<a href="https://thedigitalpress.org/failing-gloriously/">Failing Gloriously</a>” is an absolute must-read.</p>
<p>I’m tired of being told I’m “brave” for talking publicly about failure. That doesn’t support anyone in their own struggles, or move the field forward in any way. Instead of telling me I’m brave, tell me why you’re afraid? And here I’m mostly talking to the senior people in the field. The people with stable jobs. Especially, let’s be honest, the senior people who are also white men. Being a student, or precariously employed, is a great reason to be reluctant to talk about failure. So is having an identity — along axes of gender, ethnicity, language, background, or other factors — that’s marginalized in the mainstream.</p>
<p>But I think there’s enough of us here on this call who those issues don’t apply to — or don’t entirely apply to — that it’s worth coming out and asking: what’s stopping you from talking about failure with regard to your work? What do you have to lose? What could we all gain?</p>
<p>You can start anywhere: talking openly at events like this. Or blog or tweet about it. Write something from a collective perspective — as a project or organization — if you don’t want to hold the weight personally. But please join me in talking about it. It’s the most meaningful step you can take towards undoing the stigma around failure so we all can learn.</p>
<p>Thank you.</p>
